CREATE DATABASE SAP;
USE SAP;
CREATE USER [DESKTOP-UH32F5A\USER] FOR LOGIN [DESKTOP-UH32F5A\USER];
ALTER ROLE db_owner ADD MEMBER [DESKTOP-UH32F5A\USER];
CREATE LOGIN GSR WITH PASSWORD = '1234';
CREATE USER GSR FOR LOGIN GSR;
ALTER ROLE db_owner ADD MEMBER GSR;

CREATE TABLE servicio_delivery (
    id_servicio VARCHAR(20) PRIMARY KEY,
    cliente VARCHAR(100) NOT NULL,
    costo_base DECIMAL(10,2) NOT NULL,
    direccion VARCHAR(200) NOT NULL,
    tarifa_envio DECIMAL(10,2) NOT NULL
);

SELECT * FROM servicio_delivery;

